export default {
    operators_add: require('./operators_add').default,
    operators_subtract: require('./operators_subtract').default,
    operators_multiply: require('./operators_multiply').default,
    operators_exponent: require('./operators_exponent').default,
    operators_divide: require('./operators_divide').default,
    operators_mod: require('./operators_mod').default,
    operators_eq: require('./operators_eq').default,
    operators_eqt: require('./operators_eqt').default,
    operators_neq: require('./operators_neq').default,
    operators_neqt: require('./operators_neqt').default,
    operators_less: require('./operators_less').default,
    operators_greater: require('./operators_greater').default,
    operators_leq: require('./operators_leq').default,
    operators_geq: require('./operators_geq').default,
    string_length: require('./string_length').default,
    string_substr: require('./string_substr').default,
    string_substring: require('./string_substring').default,
    string_includes: require('./string_includes').default,
    string_startsWith: require('./string_startsWith').default,
    string_endsWith: require('./string_endsWith').default,
    array_every: require('./array_every').default,
};